package santa

/** Canonical JVM proof bytes for four comparison cases used by the
  * sigma-rust prover-vs-JVM-prover investigation.
  *
  * Generated by `POST /avl-proof` on 2026-07-06.  Each case's proofDigest
  * has been independently verified as `blake2b256(proofBytes)`.
  *
  * Cases:
  *   1. Empty tree, 3 inserts, no Lookup
  *   2. Empty tree, 3 inserts + 1 Lookup (inline)      — differs by 1 direction byte
  *   3. Seeded tree (3 committed entries), 1 insert + 1 Lookup (28474 pattern)
  *   4. Seeded tree (3 committed entries), 1 insert only (control)
  */
object AvlProofComparison {

  // ── test vectors ────────────────────────────────────────────────────────
  // Keys: 32× "aa", "bb", "cc", "dd"
  // Values: "01020304", "05060708", "090a0b0c", "0d0e0f10"

  // ── Case 1: empty tree, 3 inserts ───────────────────────────────────────

  val Case1 = Case(
    desc    = "empty tree, 3 inserts, no Lookup",
    keyLen  = 32,
    valLen  = None,
    init    = Nil,
    ops     = List(
      Op("Insert", K.a, Some(V.v1)),
      Op("Insert", K.b, Some(V.v2)),
      Op("Insert", K.c, Some(V.v3))
    ),
    proof   = "020000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000400",
    pDigest = "0d2933468972b3d505168dbc31dd1370f3eaebb1f4156d4494fc73d804366594",
    tDigest = "8d7b251f200d7bb3bf0eb1f9f460377a3d2bb163769d3724e77339eeb1e06f4102"
  )

  // ── Case 2: empty tree, 3 inserts + Lookup ──────────────────────────────

  val Case2 = Case(
    desc    = "empty tree, 3 inserts + 1 Lookup (inline)",
    keyLen  = 32,
    valLen  = None,
    init    = Nil,
    ops     = List(
      Op("Insert", K.a, Some(V.v1)),
      Op("Insert", K.b, Some(V.v2)),
      Op("Insert", K.c, Some(V.v3)),
      Op("Lookup", K.a, None)
    ),
    proof   = "020000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000408",
    pDigest = "e93220737e01e5b54db6068e41d85418f6d94406b3be8ec4a66c7f97c6513de3",
    tDigest = "8d7b251f200d7bb3bf0eb1f9f460377a3d2bb163769d3724e77339eeb1e06f4102"
  )

  // ── Case 3: seeded tree, insert + Lookup (28474 pattern) ─────────────────

  val Case3 = Case(
    desc    = "seeded tree (3 entries), 1 insert + 1 Lookup (28474 pattern)",
    keyLen  = 32,
    valLen  = None,
    init    = List(Kv(K.a, V.v1), Kv(K.b, V.v2), Kv(K.c, V.v3)),
    ops     = List(
      Op("Insert", K.d, Some(V.v4)),
      Op("Lookup", K.a, None)
    ),
    proof   = "0344cfd4671a6f0b122ed4fa31f236ddbe1bd1b74897634eefb8131c975f52746402aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb000000040102030400034a89e7eae4f1b9317fed4cedaf6cfaeb1db251fe121fa86df2b8f41f5942d89502ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000004090a0b0c00000404",
    pDigest = "df6602535205dcb10d610db5d0e6bd2aa7efa5a6709565b2647db7623d146656",
    tDigest = "a745f5c10181f6d4b8c2aa095982168071ef104481d0878ada642beed9ca5c1f03"
  )

  // ── Case 4: seeded tree, insert only (control) ───────────────────────────

  val Case4 = Case(
    desc    = "seeded tree (3 entries), 1 insert only (control)",
    keyLen  = 32,
    valLen  = None,
    init    = List(Kv(K.a, V.v1), Kv(K.b, V.v2), Kv(K.c, V.v3)),
    ops     = List(
      Op("Insert", K.d, Some(V.v4))
    ),
    proof   = "03fec0ef32a70153f4561c58d71f62eef89a29fccd207642aa5695dc1f42fc1ea4034a89e7eae4f1b9317fed4cedaf6cfaeb1db251fe121fa86df2b8f41f5942d89502ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000004090a0b0c00000400",
    pDigest = "e4dbcc427879408402a9a6ad1c358f03e029b8d27aadf943ef0a76fecd249aef",
    tDigest = "a745f5c10181f6d4b8c2aa095982168071ef104481d0878ada642beed9ca5c1f03"
  )

  val All: List[Case] = List(Case1, Case2, Case3, Case4)

  // ── helpers ──────────────────────────────────────────────────────────────

  /** Shared key constants (all 32 bytes, padded with the given hex byte). */
  object K {
    def pad(b: Int): String = f"${b}%02x" * 32
    val a = pad(0xaa)
    val b = pad(0xbb)
    val c = pad(0xcc)
    val d = pad(0xdd)
  }
  object V {
    val v1 = "01020304"
    val v2 = "05060708"
    val v3 = "090a0b0c"
    val v4 = "0d0e0f10"
  }

  case class Case(
    desc:    String,
    keyLen:  Int,
    valLen:  Option[Int],
    init:    List[Kv],
    ops:     List[Op],
    proof:   String,
    pDigest: String,
    tDigest: String
  )
  case class Kv(key: String, value: String)
  case class Op(kind: String, key: String, value: Option[String])
}
