package santa

import io.circe.Json
import io.circe.parser.{parse => parseJson}

/** Vendored authds avl_verify vectors: ergots' 37 reachable verifier fixtures supply the
  * INPUTS (config, startingDigestHex, proofHex, operations); every expectation is
  * re-derived from the JVM `BatchAVLVerifier`. The fixtures' own
  * `expectedNewDigestHex` / `expectedResultsHex` are Rust-blessed (generated by
  * `ergo_avltree_rust`) and are never read here — see docs/specs/authds-tier.md
  * "vendor the inputs, re-bless every expectation".
  *
  * Two independent reasons not to read them:
  *   1. Provenance — importing a Rust expectation makes the vector structurally
  *      incapable of catching a Rust-vs-JVM verifier divergence.
  *   2. Resolution — the fixture shape COLLAPSES three distinct outcomes into one
  *      `expectedNewDigestHex: null` (proof rejected / an operation failed /
  *      poisoned mid-batch). `santa-authds/v1` keeps `proof_accepted`, per-op
  *      `results`, and `new_digest_hex` apart, so re-blessing enriches as well as
  *      re-anchors.
  *
  * The JVM-vs-Rust comparison lives in `VendoredAuthdsAvlVerifyTest` on purpose:
  * this object must have no reference to the fixtures' expectation fields at all.
  */
object VendoredAuthdsAvlVerify {

  val Op = "AvlVerify.ergots_corpus"
  val Source = "ergots:packages/avltree/test/fixtures/avltree"

  /** The committed vector this blesser owns — the artifact every conformer is
    * graded against. Read back by the guard test; never written to by it. */
  val VectorPath: java.nio.file.Path =
    java.nio.file.Paths.get("..", "vectors", "authds", "any", "vendored", s"$Op.json")

  private val seedDir =
    java.nio.file.Paths.get("src", "test", "resources", "ergots-avltree", "verifier")

  /** One vendored fixture. `file` is the FILENAME — the only thing that can
    * honestly name the upstream path — and `name` is the fixture's own internal
    * label. `require`d equal on construction: if they ever disagree, `source`
    * built from either one would be a lie about where the input came from, and
    * validate's prefix check could not see it. */
  case class Seed(file: String, json: Json) {
    val stem: String = file.stripSuffix(".json")
    val name: String = json.hcursor.get[String]("name")
      .fold(e => sys.error(s"fixture $file has no name: $e"), identity)
    require(name == stem,
      s"vendored fixture $file declares name '$name' — filename and internal name must agree, " +
        "otherwise the entry's `source` points at a file that does not exist")
  }

  /** The vendored fixtures, filename-sorted. Public so the comparison test reads
    * the same files through the same listing (one seed-reading path). */
  def seeds: Vector[Seed] = {
    val files = java.nio.file.Files.list(seedDir).toArray
      .map(_.asInstanceOf[java.nio.file.Path])
      .filter(_.toString.endsWith(".json"))
      .sortBy(_.getFileName.toString)
      .toVector
    require(files.nonEmpty, s"no vendored verifier fixtures under $seedDir")
    files.map { p =>
      val json = parseJson(new String(java.nio.file.Files.readAllBytes(p), "UTF-8"))
        .fold(e => sys.error(s"bad fixture $p: $e"), identity)
      Seed(p.getFileName.toString, json)
    }
  }

  /** The ONE decode path — main scope, shared with the rudolph control arm
    * (Task 9). Never re-implement the decode here. */
  def derive(entry: Json): AvlVerifierBlesser.VerifyOutcome =
    AvlVerifierBlesser.deriveFromEntry(entry)

  /** Fixture op tags carry through unchanged; `delta` becomes a decimal STRING
    * (Long range — a pre-emptive application of the eval tier's Long-as-string
    * rule: a JSON number loses precision past 2^53. No `delta` in the current
    * corpus is anywhere near that bound — the largest `|delta|` is 100 — this
    * guards a future fixture, not an existing one). Absent optionals are
    * OMITTED rather than nulled: the schema's
    * op_item has `additionalProperties: false` with `value_hex`/`delta` optional
    * and NOT nullable, so a `"delta": null` would fail validation. (Contrast the
    * four `settings` fields, which ARE required-and-nullable — see `extract`.)
    * Identical mapping to `VendoredAuthdsAvlProve.opToJson`. */
  private def opToJson(j: Json): Json = {
    val c = j.hcursor
    val base = List(
      Some("tag" -> Json.fromString(c.get[String]("tag").toOption.get)),
      Some("key_hex" -> Json.fromString(c.get[String]("keyHex").toOption.get)),
      c.get[String]("valueHex").toOption.map(v => "value_hex" -> Json.fromString(v)),
      c.get[Long]("delta").toOption.map(d => "delta" -> Json.fromString(d.toString))
    ).flatten
    Json.obj(base: _*)
  }

  /** A `settings` field that is required-and-nullable in santa-authds/v1: emit an
    * explicit JSON null when the fixture leaves it unset, never omit the key. */
  private def optInt(c: io.circe.ACursor, field: String): Json =
    c.get[Option[Int]](field).toOption.flatten.map(Json.fromInt).getOrElse(Json.Null)

  def extract(): Map[String, Json] = {
    val entries = seeds.map { seed =>
      val c = seed.json.hcursor
      val cfg = c.downField("config")
      val settings = Json.obj(
        "key_length" -> Json.fromInt(cfg.get[Int]("keyLength").toOption.get),
        "value_length" -> optInt(cfg, "valueLengthOpt"),
        "max_num_operations" -> optInt(cfg, "maxNumOperations"),
        "max_deletes" -> optInt(cfg, "maxDeletes")
      )
      val payload = Json.obj(
        "starting_digest_hex" -> Json.fromString(c.get[String]("startingDigestHex").toOption.get),
        "proof_hex" -> Json.fromString(c.get[String]("proofHex").toOption.get),
        "operations" -> Json.arr(c.downField("operations").values.get.toVector.map(opToJson): _*)
      )
      val out = derive(Json.obj("settings" -> settings, "payload" -> payload))
      Json.obj(
        "name" -> Json.fromString(seed.name),
        // keyed off the FILENAME, not the fixture's internal name — `source` must
        // name a file that actually exists upstream (Seed require()s the two agree)
        "source" -> Json.fromString(s"$Source/${seed.file}"),
        "kind" -> Json.fromString("avl_verify"),
        "settings" -> settings,
        "payload" -> payload,
        "expected" -> Json.obj(
          "proof_accepted" -> Json.fromBoolean(out.proofAccepted),
          // `results` is [] whenever the proof did not anchor (never omitted) — but not
          // ONLY then: an anchored proof with zero operations (`batch-0ops`) also produces
          // `results: []`. The invariant validate enforces is one-directional: accepted =>
          // results.length == operations.length; not-accepted => results == []. Otherwise
          // one entry per operation, including the ones that run after the verifier is
          // already poisoned.
          "results" -> Json.arr(out.results.map { r =>
            Json.obj(
              "ok" -> Json.fromBoolean(r.ok),
              "value" -> r.value.map(Json.fromString).getOrElse(Json.Null)
            )
          }: _*),
          "new_digest_hex" -> out.newDigestHex.map(Json.fromString).getOrElse(Json.Null)
        )
      )
    }
    Map(Op -> Json.obj(
      "schema" -> Json.fromString("santa-authds/v1"),
      "op" -> Json.fromString("authds:vendored:avl-verify"),
      "blessed_by" -> Json.fromString("jvm:scrypto-3.0.0"),
      "source" -> Json.fromString(Source),
      "entries" -> Json.arr(entries: _*)
    ))
  }

  /** The ONE serialization of an envelope. Writer and currency check share it, so
    * "the committed file equals a fresh build" cannot drift into a formatting
    * argument between two renderers. */
  def render(envelope: Json): String = envelope.spaces2

  /** Persist. Mirrors VendoredAuthdsAvlProve.writeVectors, slug-collision-guarded.
    * Driven by the currency test's opt-in regenerate
    * (`SANTA_WRITE_AUTHDS=1 sbt test`) — the default test run only READS the
    * committed vector, so a hand-edit fails the guard instead of being silently
    * overwritten. */
  def writeVectors(vectors: Map[String, Json], outDir: java.nio.file.Path): Unit = {
    java.nio.file.Files.createDirectories(outDir)
    val collisions = vectors.keys.groupBy(SpecExtract.slug).filter(_._2.size > 1)
    if (collisions.nonEmpty)
      sys.error("VendoredAuthdsAvlVerify.writeVectors: slug collision would silently drop entries — " +
        collisions.map { case (s, ops) => s"'$s.json' <- ${ops.mkString(" / ")}" }.mkString("; "))
    vectors.foreach { case (op, json) =>
      java.nio.file.Files.write(outDir.resolve(s"${SpecExtract.slug(op)}.json"),
        render(json).getBytes(java.nio.charset.StandardCharsets.UTF_8))
    }
  }
}
