package santa

import io.circe.Json
import io.circe.parser.{parse => parseJson}

/** Vendored authds avl_prove vectors: ergots' 10 prover fixtures supply the
  * INPUTS (config, operations, genProofAfter); every expectation is re-derived
  * from the JVM `BatchAVLProver`. The fixtures' own expectedProofs /
  * expectedDigests are Rust-blessed (generated by ergo_avltree_rust) and are
  * never read here — see docs/specs/authds-tier.md "vendor the inputs, re-bless
  * every expectation". Reading them would make the vectors structurally
  * incapable of catching a Rust-vs-JVM prover divergence.
  *
  * The JVM-vs-Rust comparison lives in `VendoredAuthdsAvlProveTest` on purpose:
  * this object must have no reference to the fixtures' expectation fields at all.
  */
object VendoredAuthdsAvlProve {

  val Op = "AvlProve.ergots_corpus"
  val Source = "ergots:packages/avltree/test/fixtures/prover"

  private val seedDir =
    java.nio.file.Paths.get("src", "test", "resources", "ergots-avltree", "prover")

  /** The vendored fixtures, name-sorted. Public so the comparison test reads the
    * same files through the same listing (one seed-reading path). */
  def seeds: Vector[Json] = {
    val files = java.nio.file.Files.list(seedDir).toArray
      .map(_.asInstanceOf[java.nio.file.Path])
      .filter(_.toString.endsWith(".json"))
      .sortBy(_.getFileName.toString)
      .toVector
    require(files.nonEmpty, s"no vendored prover fixtures under $seedDir")
    files.map { p =>
      parseJson(new String(java.nio.file.Files.readAllBytes(p), "UTF-8"))
        .fold(e => sys.error(s"bad fixture $p: $e"), identity)
    }
  }

  /** The ONE decode path — main scope, shared with the rudolph control arm
    * (Task 9). Never re-implement the decode here. */
  def derive(entry: Json): (List[String], List[String]) =
    AvlProofGenerator.deriveFromEntry(entry)

  /** Fixture op tags carry through unchanged; `delta` becomes a decimal STRING
    * (Long range — an i64-boundary delta loses precision as a JSON number).
    * Absent optionals are OMITTED here rather than nulled: the schema's op_item
    * has `additionalProperties: false` with `value_hex`/`delta` optional and
    * NOT nullable, so a `"delta": null` would fail validation. (Contrast
    * `settings.value_length`, which IS required-and-nullable — see `extract`.) */
  private def opToJson(j: Json): Json = {
    val c = j.hcursor
    val base = List(
      Some("tag" -> Json.fromString(c.get[String]("tag").toOption.get)),
      Some("key_hex" -> Json.fromString(c.get[String]("keyHex").toOption.get)),
      c.get[String]("valueHex").toOption.map(v => "value_hex" -> Json.fromString(v)),
      c.get[Long]("delta").toOption.map(d => "delta" -> Json.fromString(d.toString))
    ).flatten
    Json.obj(base: _*)
  }

  def extract(): Map[String, Json] = {
    val entries = seeds.map { fx =>
      val c = fx.hcursor
      val name = c.get[String]("name").toOption.get
      val cfg = c.downField("config")
      // `value_length` is required-and-nullable in santa-authds/v1: emit an
      // explicit null when the fixture has no fixed value length, never omit it.
      val settings = Json.obj(
        "key_length" -> Json.fromInt(cfg.get[Int]("keyLength").toOption.get),
        "value_length" -> cfg.get[Option[Int]]("valueLengthOpt").toOption.flatten
          .map(Json.fromInt).getOrElse(Json.Null)
      )
      val payload = Json.obj(
        "operations" -> Json.arr(c.downField("operations").values.get.toVector.map(opToJson): _*),
        "gen_proof_after" -> Json.arr(
          c.get[List[Int]]("genProofAfter").toOption.get.map(Json.fromInt): _*)
      )
      val stub = Json.obj("settings" -> settings, "payload" -> payload)
      val (proofs, digests) = derive(stub)
      Json.obj(
        "name" -> Json.fromString(name),
        "source" -> Json.fromString(s"$Source/$name.json"),
        "kind" -> Json.fromString("avl_prove"),
        "settings" -> settings,
        "payload" -> payload,
        "expected" -> Json.obj(
          "proofs" -> Json.arr(proofs.map(Json.fromString): _*),
          "digests" -> Json.arr(digests.map(Json.fromString): _*)
        )
      )
    }
    Map(Op -> Json.obj(
      "schema" -> Json.fromString("santa-authds/v1"),
      "op" -> Json.fromString("authds:vendored:avl-prove"),
      "blessed_by" -> Json.fromString("jvm:scrypto-3.0.0"),
      "source" -> Json.fromString(Source),
      "entries" -> Json.arr(entries: _*)
    ))
  }

  /** Persist to a staging dir (build artifact; cp into vectors/authds/any/vendored/
    * once inspected). Mirrors VendoredWireErgots.writeVectors, slug-collision-guarded. */
  def writeVectors(vectors: Map[String, Json], outDir: java.nio.file.Path): Unit = {
    java.nio.file.Files.createDirectories(outDir)
    val collisions = vectors.keys.groupBy(SpecExtract.slug).filter(_._2.size > 1)
    if (collisions.nonEmpty)
      sys.error("VendoredAuthdsAvlProve.writeVectors: slug collision would silently drop entries — " +
        collisions.map { case (s, ops) => s"'$s.json' <- ${ops.mkString(" / ")}" }.mkString("; "))
    vectors.foreach { case (op, json) =>
      java.nio.file.Files.write(outDir.resolve(s"${SpecExtract.slug(op)}.json"),
        json.spaces2.getBytes(java.nio.charset.StandardCharsets.UTF_8))
    }
  }
}
